# [TRIAL: doc-pack] -----------------------------------------------------------
# Self-contained model for the Document Pack trial feature.
#
# To DISABLE the trial without code removal:  set env DOC_PACK_TRIAL_ENABLED=false
# To FULLY REMOVE the trial:
#   1. git revert the [trial:doc-pack] commit
#   2. (optional) DROP TABLE payroll_doc_packs;
# Nothing else in the codebase references this model directly, so removing it
# touches no other module beyond a single import line in app/__init__.py.
# -----------------------------------------------------------------------------

from datetime import datetime

from app import db


class PayrollDocPack(db.Model):
    """ZIP file representing one month's complete document evidence trail for
    a payroll period — generated by the staff via "Generate Document Pack",
    re-uploaded after the staff drops in the EPFO/ESIC portal downloads.

    During the trial we store the ENTIRE uploaded ZIP as a single BYTEA blob.
    If the trial succeeds, Phase 2 will unpack into individual records so the
    client portal can show each file separately.
    """
    __tablename__ = 'payroll_doc_packs'

    id               = db.Column(db.Integer, primary_key=True)
    payroll_id       = db.Column(db.Integer,
                                 db.ForeignKey('monthly_payrolls.id', ondelete='CASCADE'),
                                 nullable=False, index=True)
    establishment_id = db.Column(db.Integer,
                                 db.ForeignKey('establishments.id', ondelete='CASCADE'),
                                 nullable=False, index=True)
    pack_name        = db.Column(db.String(255), nullable=False)
    file_data        = db.Column(db.LargeBinary, nullable=False)
    file_size        = db.Column(db.Integer, nullable=False)
    uploaded_by      = db.Column(db.String(100), nullable=True)
    uploaded_at      = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)

    @property
    def size_kb(self):
        return round(self.file_size / 1024, 1)

    @property
    def size_mb(self):
        return round(self.file_size / (1024 * 1024), 2)

    def __repr__(self):
        return f'<PayrollDocPack {self.pack_name} payroll={self.payroll_id}>'
